In [3]:
import numpy as np
import json
import pandas as pd

In [5]:
df = pd.read_csv('data/pad.csv')
inputSeq = np.array(df[0:50000])
print(np.array(inputSeq)) 
maxSeqLen = len(inputSeq[0])
print(maxSeqLen)

[[   0    0    0 ...    0   23   15]
 [   0    0    0 ...   23   15    4]
 [   0    0    0 ...   15    4   46]
 ...
 [   0    0    0 ... 4672   25   68]
 [   0    0    0 ...   25   68  452]
 [   0    0    0 ...   68  452   12]]
20
